// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATlwSMxWVj3DMRBLd9d_1dyx2F8k7cBVw',
    appId: '1:96285559448:web:0ec85b2e27d600b7f89eed',
    messagingSenderId: '96285559448',
    projectId: 'fir-test-project-f609f',
    authDomain: 'fir-test-project-f609f.firebaseapp.com',
    storageBucket: 'fir-test-project-f609f.appspot.com',
    measurementId: 'G-F8XFW1ZV5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChttXA-vxz9wyBM-YKqL9TA7oBMcSKc6M',
    appId: '1:96285559448:android:3fd813330a70f32bf89eed',
    messagingSenderId: '96285559448',
    projectId: 'fir-test-project-f609f',
    storageBucket: 'fir-test-project-f609f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQuTDcCGdY_DoSix46AZ3zrRRrfIPXZKI',
    appId: '1:96285559448:ios:12a127c756f6263df89eed',
    messagingSenderId: '96285559448',
    projectId: 'fir-test-project-f609f',
    storageBucket: 'fir-test-project-f609f.appspot.com',
    iosClientId: '96285559448-s8v43ml27m80tc4ht2usar2a19lqsmgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoTesting',
  );
}
